### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by xImSebi** [Fishw4re/Shared-SkinChanger#2]
I have setup a new Ubuntu Server and executed "apt-get install nodejs npm"
then uploaded the index.js
and executed the npm command in the same folder as i uploaded the index.js

then downloaded the skins.lua and edited the DEFAULT_URL to ws://ip-of-my-server:8080
i also have subscribed to both workshop files in gamesense forums...

when i load the lua i get the following error:
[gamesense] [WS] Error: nil
[gamesense] [WS] Connection closed: code=1006 reason= was_clean=false

i hope you can help me

**Comment by ErrorDodo** [comment]
Are you running the file on the server?

**Comment by xImSebi** [comment]
You mean the index.js? Yes this file is uploaded on the server and should be also running... (i executed the npm command in the same folder as i uploaded the index.js)

**Comment by ErrorDodo** [comment]
No, you need to do 

node index.js

The file isn't run automatically.

**Comment by xImSebi** [comment]
Ok i started it in a screen... and its working now... thank you :)
